name: servatrice

services:
  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: servatrice
      MYSQL_USER: servatrice
    volumes:
      - ${PWD}/servatrice/servatrice.sql:/docker-entrypoint-initdb.d/servatrice.sql
    networks:
      - net
    healthcheck:
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 60s
      start_interval: 5s
      test: healthcheck.sh --connect || exit 1

  servatrice:
    image: ghcr.io/papabeardoes/servatrice:latest
    container_name: servatrice
    restart: unless-stopped
    entrypoint: "/bin/bash -c 'sleep 10; servatrice --config /tmp/servatrice.ini --log-to-console'"
    volumes:
      - ${PWD}/servatrice/docker/servatrice-docker.ini:/tmp/servatrice.ini
    networks:
      - net
    ports:
      - 4747:4747
      - 4748:4748
    depends_on:
      db:
        condition: service_healthy

networks:
  net:
    driver: bridge
    attachable: true